### ISSUE TITLE
Can I resume learning with fold?

### ISSUE THREAD

**Issue by tenajima** [nyanp/nyaggle#31]
I often use preemptive instance.
So, I want to resume learning if the instance is shut down.
`nyaggle` can resume learning ? If not now, is `nyaggle` planning to implement it?

**Comment by nyanp** [comment]
Thanks for your comment! This is the first issue posted by an account other than me :)


`run_experiment` does not support resuming an experiment, but `Experiment` class does.

```python
from nyaggle.experiment import Experiment

logging_dir = ...

with Experiment(logging_dir, with_mlflow=True) as e:
    e.log_metric('CV', 0.97)

# continue from the existing experiment
with Experiment.continue_from(logging_dir) as e:
    e.log_metric('LB', 0.95)
```

Since `run_experiment` is implemented using `Experiment` (see [code](https://github.com/nyanp/nyaggle/blob/master/nyaggle/experiment/run.py#L189)), you can implement your code similar to `run_experiment` by your own :) I hope this helps.

**Comment by tenajima** [comment]
Thank you for your reply !
I'll try :)
