### ISSUE TITLE
Starter notebook is in progress.

### ISSUE THREAD

**Issue by wakame1367** [nyanp/nyaggle#49]
What content should be included?
below link is draft.
https://drive.google.com/open?id=1aSiplVhB9Hjcj8Ib-A9zkAjEgykpllH4

**Comment by nyanp** [comment]
Oh, cool!
Since nyaggle is a collection of independent utility functions, I think we don't need to visit all modules (this use case should rather be covered by the API reference). 

If the notebook covers an end-to-end modeling process in typical tabular data competition, it would be very valuable for data-science beginners. In that case, for example, the content would be consist of the following steps:

1. load train.csv, test.csv, sample_submission.csv
1. manual feature engineering
1. save/load features using `feature_store` (`cached_feature` decorator is suitable for a single notebook)
1. (optional) check trian/test difference by `adversarial_validation`
1. call `run_experiment` with mlflow
1. see the result in the notebook and localhost:5000

The following notebook will be helpful as examples with similar purpose.

- [featuretools with Kaggle HomeCredit competition](https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Loan%20Repayment/notebooks/Automated%20Loan%20Repayment.ipynb)
- [H2O.ai](https://github.com/h2oai/h2o-3/blob/master/examples/deeplearning/notebooks/deeplearning_anomaly_detection.ipynb)
- [PyTorch](https://pytorch.org/tutorials/beginner/transformer_tutorial.html)

**Comment by wakamezake** [comment]
Starter notebook moved.
[nyaggle-tutorial-for-titanic.ipynb](https://github.com/wakamezake/nyaggle_sample/blob/master/notebooks/nyaggle-tutorial-for-titanic.ipynb)
